hg38_ref_data:
  fasta: "data/hg38_ref_data/chrY.fa.gz"
  gene_def: "data/hg38_ref_data/gene_definition_hg38.v1.tab"
species:
  mGorGor1_gorilla:
    fasta: "https://genomeark.s3.amazonaws.com/species/Gorilla_gorilla/mGorGor1/assembly_verkko_1.1-0.2-freeze/mGorGor1.chrXY.20221111.fasta.gz"
    faidx: "https://genomeark.s3.amazonaws.com/species/Gorilla_gorilla/mGorGor1/assembly_verkko_1.1-0.2-freeze/mGorGor1.chrXY.20221111.fasta.gz.gzi"
    repeatMasker: "data/repeat_masker_t2t_primates/Gorilla_FinalAnnotations_June2023_v2.sort.out"
    readsize: 101
    length: 65269191
    ref_fasta: "/scratch16/rmccoy22/abiddan1/t2t_primates_analyses/reference_data/ref/Gorilla/mGorGor1.fa"
    indivs:
      Abe: "/data/mschatz1/qiuhuili/project/primate/files/cram/Abe/T2T.cram"
      Azizi: "/data/mschatz1/qiuhuili/project/primate/files/cram/Azizi/T2T.cram"
      Banjo: "/data/mschatz1/qiuhuili/project/primate/files/cram/Banjo/T2T.cram"
      Kaisi: "/data/mschatz1/qiuhuili/project/primate/files/cram/Kaisi/T2T.cram"
      Mkubwa: "/data/mschatz1/qiuhuili/project/primate/files/cram/Mkubwa/T2T.cram"
      Tzambo: "/data/mschatz1/qiuhuili/project/primate/files/cram/Tzambo/T2T.cram" 
  mPanPan1_bonobo: 
    fasta: "https://genomeark.s3.amazonaws.com/species/Pan_paniscus/mPanPan1/assembly_verkko_1.1-0.1-freeze/mPanPan1.chrXY.20221111.fasta.gz"
    faidx: "https://genomeark.s3.amazonaws.com/species/Pan_paniscus/mPanPan1/assembly_verkko_1.1-0.1-freeze/mPanPan1.chrXY.20221111.fasta.gz.gzi"
    repeatMasker: "data/repeat_masker_t2t_primates/Bonobo_FinalAnnotations_June2023_v2.sort.out"
    readsize: 101
    length: 46925665
    ref_fasta: "/scratch16/rmccoy22/abiddan1/t2t_primates_analyses/reference_data/ref/Bonobo/mPanPan1.fa"
    indivs:
      Bono: "/data/mschatz1/qiuhuili/project/primate/files/cram/Bono/T2T.cram"
      Desmond: "/data/mschatz1/qiuhuili/project/primate/files/cram/Desmond/T2T.cram"
  mPanTro3_chimp:
    fasta: "https://genomeark.s3.amazonaws.com/species/Pan_troglodytes/mPanTro3/assembly_verkko_1.1-hic-freeze/mPanTro3.chrXY.20221111.fasta.gz"
    faidx: "https://genomeark.s3.amazonaws.com/species/Pan_troglodytes/mPanTro3/assembly_verkko_1.1-hic-freeze/mPanTro3.chrXY.20221111.fasta.gz.gzi"
    repeatMasker: "data/repeat_masker_t2t_primates/Gorilla_FinalAnnotations_June2023_v2.sort.out"
    readsize: 101
    length: 36445859
    ref_fasta: "/home/abiddan1/scratch16/t2t_primates_analyses/reference_data/ref/chimpanzee/mPanTro3.fa"
    indivs:
      Akwaya-Jean: "/data/mschatz1/qiuhuili/project/primate/files/cram/Akwaya-Jean/T2T.cram"
      Alfred: "/data/mschatz1/qiuhuili/project/primate/files/cram/Alfred/T2T.cram"
      Athanga: "/data/mschatz1/qiuhuili/project/primate/files/cram/Athanga/T2T.cram"
      Basho: "/data/mschatz1/qiuhuili/project/primate/files/cram/Basho/T2T.cram"
      Bosco: "/data/mschatz1/qiuhuili/project/primate/files/cram/Bosco/T2T.cram"
      Brigitta: "/data/mschatz1/qiuhuili/project/primate/files/cram/Brigitta/T2T.cram"
      Bwambale: "/data/mschatz1/qiuhuili/project/primate/files/cram/Bwambale/T2T.cram"
      Clint: "/data/mschatz1/qiuhuili/project/primate/files/cram/Clint/T2T.cram"
      Damian: "/data/mschatz1/qiuhuili/project/primate/files/cram/Damian/T2T.cram"
      Gamin: "/data/mschatz1/qiuhuili/project/primate/files/cram/Gamin/T2T.cram"
      Koby: "/data/mschatz1/qiuhuili/project/primate/files/cram/Koby/T2T.cram"
      Koto: "/data/mschatz1/qiuhuili/project/primate/files/cram/Koto/T2T.cram"
      Mgbadolite: "/data/mschatz1/qiuhuili/project/primate/files/cram/Mgbadolite/T2T.cram"
      Mike: "/data/mschatz1/qiuhuili/project/primate/files/cram/Mike/T2T.cram"
      Padda: "/data/mschatz1/qiuhuili/project/primate/files/cram/Padda/T2T.cram"
      SeppToni: "/data/mschatz1/qiuhuili/project/primate/files/cram/SeppToni/T2T.cram"
      Taweh: "/data/mschatz1/qiuhuili/project/primate/files/cram/Taweh/T2T.cram"
      Tongo: "/data/mschatz1/qiuhuili/project/primate/files/cram/Tongo/T2T.cram"
      Vaillant: "/data/mschatz1/qiuhuili/project/primate/files/cram/Vaillant/T2T.cram"
      Vincent: "/data/mschatz1/qiuhuili/project/primate/files/cram/Vincent/T2T.cram"
      Washu: "/data/mschatz1/qiuhuili/project/primate/files/cram/Washu/T2T.cram"
      Yogui: "/data/mschatz1/qiuhuili/project/primate/files/cram/Yogui/T2T.cram"
  mPonAbel_orangutan_sumatra:
    fasta: "https://genomeark.s3.amazonaws.com/species/Pongo_abelii/mPonAbe1/assembly_verkko_1.1-hic-freeze/mPonAbe1.chrXY.20221111.fasta.gz"
    faidx: "https://genomeark.s3.amazonaws.com/species/Pongo_abelii/mPonAbe1/assembly_verkko_1.1-hic-freeze/mPonAbe1.chrXY.20221111.fasta.gz.gzi"
    repeatMasker: "data/repeat_masker_t2t_primates/Sumatran_FinalAnnotations_June2023_v2.sort.out"
    readsize: 101
    ref_fasta: "/home/abiddan1/scratch16/t2t_primates_analyses/reference_data/ref/Sumatran/mPonAbe1.fa"
    length: 67808326
    indivs:
      Buschi: "/data/mschatz1/qiuhuili/project/primate/files/cram/Buschi/T2T.cram"
  mPonPyg2_orangutan_borneo:
    fasta: "https://genomeark.s3.amazonaws.com/species/Pongo_pygmaeus/mPonPyg2/assembly_verkko_1.1-hic-freeze/mPonPyg2.chrXY.20221111.fasta.gz"
    faidx: "https://genomeark.s3.amazonaws.com/species/Pongo_pygmaeus/mPonPyg2/assembly_verkko_1.1-hic-freeze/mPonPyg2.chrXY.20221111.fasta.gz.gzi"
    repeatMasker: "data/repeat_masker_t2t_primates/Bornean_FinalAnnotations_June2023_v2.sort.out"
    readsize: 101
    length: 49349692
    ref_fasta: "/home/abiddan1/scratch16/t2t_primates_analyses/reference_data/ref/Bornean/mPonPyg2.fa"
    indivs:
      Napoleon: "/data/mschatz1/qiuhuili/project/primate/files/cram/Napoleon/T2T.cram"
  mHomSapChm13_homo_sapien:
    fasta: "https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/analysis_set/chm13v2.0.fa.gz"
    faidx: "https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/analysis_set/chm13v2.0.fa.gz.gzi"
    repeatMasker: "data/repeat_masker_t2t_primates/CHM13v2.0_XY_FinalAnnotations_June2023_v2.sort.out"
    readsize: 101
    length: 62460029

